### ISSUE TITLE
Disable comments for specific page?

### ISSUE THREAD

**Issue by mhsabbagh** [splitbrain/dokuwiki-plugin-disqus#12]
Hello.

I have a lot of pages on my wiki and almost 99.9% of them should have comments, therefore I've edited my template to implement this plugin on all pages as shown in the documents.

However, some pages should not have comments, so is there macro like `~~ Disqus Off ~~` that I can use?

Thanks.

**Comment by splitbrain** [comment]
no. but you can add an if clause around the embed in your template checking the content of $ID
